### ISSUE TITLE
startup fail

### ISSUE THREAD

**Issue by mrcoffee1026** [Slimefun-Addon-Community/SoundMuffler#8]
[10:27:04] [Server thread/INFO]: [SoundMuffler] Enabling SoundMuffler vDEV - 20 (git cde78980)
[10:27:04] [Server thread/ERROR]: Error occurred while enabling SoundMuffler vDEV - 20 (git cde78980) (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason
	at dev.j3fftw.soundmuffler.SoundMufflerMachine.<init>(SoundMufflerMachine.java:123) ~[?:?]
	at dev.j3fftw.soundmuffler.SoundMuffler.onEnable(SoundMuffler.java:34) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-683]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.16.5.jar:git-Paper-683]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-683]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-683]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-683]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:592) ~[patched_1.16.5.jar:git-Paper-683]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-683]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-683]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-683]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.UnregisterReason
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-683]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-683]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 12 more
[10:27:04] [Server thread/INFO]: [SoundMuffler] Disabling SoundMuffler vDEV - 20 (git cde78980)

Paper git-Paper-683 (MC: 1.16.5)
Slimefun DEV - 912 (git f4b47331)
Metrics-Module #22
Java 11

Installed Addons: (34)
  GlobalWarming vDEV - 9 (git d21d264b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  FoxyMachines vDEV - 45 (git ce4f8193)
  SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
  SensibleToolbox vDEV - 40 (git f3e782d3)
  SimpleMaterialGenerators vDEV - 6 (git 2083e132)
  DynaTech vDEV - 116 (git dfb785ea)
  ExtraGear vDEV - 12 (git 4570ea2c)
  MoreTools vDEV - 10 (git 660e2ce6)
  InfinityExpansion vDEV - 111 (git 461a3fd6)
  SFCalc vDEV - 22 (git 4e764de8)
  ElectricSpawners vDEV - 22 (git 4cb2c56b)
  ExtraHeads vDEV - 21 (git a2c68d59)
  MobCapturer vDEV - 15 (git a42c9e0c)
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  PrivateStorage vDEV - 17 (git 43d35d74)
  TranscEndence vDEV - 33 (git e9b4de1a)
  GeneticChickengineering vDEV - 13 (git 37cffcbb)
  FluffyMachines vDEV - 80 (git 33ea9284)
  CMI v8.8.4.1
  ChestTerminal vDEV - 43 (git 3096bab5)
  DyedBackpacks vDEV - 15 (git 5f5e8b9e)
  SoundMuffler vDEV - 20 (git cde78980)
  SlimefunWarfare vDEV - 31 (git cc372360)
  EcoPower vDEV - 4 (git 2a08d31d)
  HotbarPets vDEV - 37 (git 63b1553e)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  ExoticGarden vDEV - 76 (git d148a362)
  Liquid vDEV - 11 (git bea52454)
  SlimeCustomizer vDEV - 6 (git 6c348829)
  LiteXpansion vDEV - 125 (git 96d1cf20)
  SimpleUtils vDEV - 8 (git 1505dfa3)
  SoulJars vDEV - 22 (git aded79dd)
  SlimyRepair vDEV - 3 (git c56293bb)
>

**Comment by J3fftw1** [comment]
update to 21
