### ISSUE TITLE
Error Spamming Console

### ISSUE THREAD

**Issue by dhfirmino** [Slimefun-Addon-Community/SoundMuffler#9]
https://pastebin.com/YmrRyHJV

**Comment by L4BORG** [comment]
We have the same issue

```[02:48:24 ERROR]: [SoundMuffler] Unhandled exception occured in onPacketSending(PacketEvent) for SoundMuffler
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:222) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:?]
        at dev.j3fftw.soundmuffler.SoundMufflerListener.lambda$onPacketSending$0(SoundMufflerListener.java:40) ~[SoundMuffler.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652) ~[?:?]
        at dev.j3fftw.soundmuffler.SoundMufflerListener.onPacketSending(SoundMufflerListener.java:42) ~[SoundMuffler.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[app:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1997) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1983) ~[app:?]
        at net.minecraft.server.players.PlayerList.broadcast(PlayerList.java:1243) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.playSound(ServerLevel.java:1503) ~[app:?]
        at net.minecraft.world.entity.animal.Sheep.shear(Sheep.java:252) ~[app:?]
        at net.minecraft.world.entity.animal.Sheep.mobInteract(Sheep.java:236) ~[app:?]
        at net.minecraft.world.entity.Mob.interact(Mob.java:1243) ~[app:?]
        at net.minecraft.world.entity.player.Player.interactOn(Player.java:1084) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2458) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.onInteraction(ServerGamePacketListenerImpl.java:2477) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2419) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:48:24 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutEntitySound@1fd996cd[
    a=net.minecraft.sounds.SoundEffect@7a55f148
    b=PLAYERS
    c=87804
    d=1.0
    e=1.0
  ]
```

Latest PaperSpigot 1.17
Latest SF and Muffler
Latest protocollib

Paper git-Paper-409 (MC: 1.17.1)
Slimefun DEV - 1008 (git 020094e0)
Metrics-Module #28
Java 17

Installed Addons: (5)
  SoundMuffler vDEV - 23 (git 2030f464)
  EcoPower vDEV - 5 (git 5c1ecd68)
  FluffyMachines vDEV - 109 (git 8d47f65d)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)



> ver ProtocolLib
[02:55:45 INFO]: ProtocolLib version 4.8.0
[02:55:45 INFO]: Provides read/write access to the Minecraft protocol.
[02:55:45 INFO]: Authors: dmulloy2 and comphenix

**Comment by mrcoffee1026** [comment]
same here

```
Slimefun DEV - 1014 (git f431aa6d)
Metrics-Module #25
Java 17

Installed Addons: (43)
  GlobalWarming vDEV - 11 (git 73ff77d4)
  Networks vDEV - 34 (git eb71c14d)
  CrystamaeHistoria vDEV - 73 (git 528ad08d)
  ExtraTools vDEV - 34 (git e84a9d59)
  FoxyMachines vDEV - 58 (git c2c2b8a7)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  SfChunkInfo vDEV - 6 (git 56940fbf)
  FNAmplifications vDEV - 73 (git 04609677)
  SimpleMaterialGenerators vDEV - 1 (git 719e1451)
  DynaTech vDEV - 165 (git 50b62512)
  ExtraGear vDEV - 13 (git c62047e2)
  Supreme vDEV - 4 (git 59c27cba)
  InfinityExpansion vDEV - 140 (git 0098d2fb)
  CMILib v1.1.2.5
  SFCalc vDEV - 36 (git 74973a41)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  ExtraHeads vDEV - 23 (git 0b59a770)
  VillagerUtil vDEV - 1 (git 0a949b19)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  PrivateStorage vDEV - 18 (git 5832db21)
  FlowerPower vDEV - 14 (git 63a37cc0)
  SlimeTinker vDEV - 74 (git 5ae433d4)
  Galactifun vDEV - 62 (git 03543cfe)
  TranscEndence vDEV - 41 (git 98d7d47e)
  FluffyMachines vDEV - 116 (git e439acf9)
  CMI v9.1.4.7
  DyedBackpacks vDEV - 17 (git 8b329e96)
  SoundMuffler vDEV - 23 (git 2030f464)
  AlchimiaVitae vDEV - 21 (git 27b788bf)
  SlimefunWarfare vDEV - 80 (git 364331cf)
  EcoPower vDEV - 5 (git 5c1ecd68)
  HotbarPets vDEV - 38 (git fa6c871d)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  DankTech2 vDEV - 4 (git 803760fb)
  Liquid vDEV - 14 (git 0f5346bf)
  LiteXpansion vDEV - 155 (git 574d551a)
  SimpleUtils vDEV - 15 (git 4250fd5e)
  ElementManipulation vDEV - 21 (git b29aaa3b)
  SoulJars vDEV - 23 (git b8358a1f)
  PotionExpansion vDEV - 5 (git e2cfcd8a)
  SlimyRepair vDEV - 4 (git 790c41cb)
>

```
